server:
  port: 8091
  error:
    # Debug tool
    include-message: always
spring:
  jpa:
    hibernate:
      # Auto create DB (none, validate, update, create-drop)
      ddl-auto: create-drop
    show-sql: false
  # In-memory DB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  # Message broker
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topic: multinode-edit-rq
      group: multinode-edit-rq-group
      trusted:
        packages: hex.multinode.storage.model.dto.
      value:
        default:
          type: hex.multinode.storage.model.dto.NodeDTO
# gRPC
grpc:
  port: 6565
